import torch
import torch.nn as nn
import math

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

def weights_init_normal(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        torch.nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find('BatchNorm2d') != -1:
        torch.nn.init.normal_(m.weight.data, 1.0, 0.02)
        torch.nn.init.constant_(m.bias.data, 0.0)
    if isinstance(m, nn.Linear):
        trunc_normal_(m.weight, std=.02)
        if isinstance(m, nn.Linear) and m.bias is not None:
            nn.init.constant_(m.bias, 0)
    elif isinstance(m, nn.LayerNorm):
        nn.init.constant_(m.bias, 0)
        nn.init.constant_(m.weight, 1.0)
##############################
#           U-NET
##############################
class UNetDown(nn.Module):
    def __init__(self, in_size, out_size, normalize=True, dropout=0.0):
        super(UNetDown, self).__init__()
        layers = [nn.Conv2d(in_size, out_size, 4, 2, 1, bias=False)]
        if normalize:
            layers.append(nn.InstanceNorm2d(out_size))
        layers.append(nn.LeakyReLU(0.2))
        if dropout:
            layers.append(nn.Dropout(dropout))
        self.model = nn.Sequential(*layers)

    def forward(self, x):
        return self.model(x)


class UNetDown_Enhanced(nn.Module):
    def __init__(self, in_size, out_size, normalize=True, dropout=0.0, use_attention=True):
        super(UNetDown_Enhanced, self).__init__()

        self.conv1 = nn.Conv2d(in_size, out_size, kernel_size=3, stride=1, padding=1, bias=False)
        self.conv2 = nn.Conv2d(out_size, out_size, kernel_size=4, stride=2, padding=1, bias=False)

        # Use InstanceNorm for batch size 1
        self.norm = nn.InstanceNorm2d(out_size) if normalize else nn.Identity()
        self.activation = nn.LeakyReLU(0.2)
        self.dropout = nn.Dropout(dropout) if dropout else nn.Identity()

        # Optional Self-Attention layer for batch size 1
        self.attention = nn.Conv2d(out_size, out_size, kernel_size=1) if use_attention else nn.Identity()

    def forward(self, x):
        out = self.conv1(x)
        out = self.conv2(out)
        out = self.norm(out)
        out = self.activation(out)
        out = self.dropout(out)

        # Apply attention if enabled
        out = out * self.attention(out)

        return out

class UNetUp(nn.Module):
    def __init__(self, in_size, out_size, dropout=0.0):
        super(UNetUp, self).__init__()
        layers = [  nn.ConvTranspose2d(in_size, out_size, 4, 2, 1, bias=False),
                    nn.InstanceNorm2d(out_size),
                    nn.ReLU(inplace=True)]
        if dropout:
            layers.append(nn.Dropout(dropout))

        self.model = nn.Sequential(*layers)

    def forward(self, x, skip_input):
        x = self.model(x)
        x = torch.cat((x, skip_input), 1)
        return x


class UNetUp_Enhanced(nn.Module):
    def __init__(self, in_size, out_size, dropout=0.0, use_attention=False):
        super(UNetUp_Enhanced, self).__init__()

        # Transposed convolution to upsample
        self.upconv = nn.ConvTranspose2d(in_size, out_size, 4, 2, 1, bias=False)

        # Optional additional convolution to refine details
        self.refine_conv = nn.Conv2d(out_size, out_size, kernel_size=3, stride=1, padding=1, bias=False)

        # InstanceNorm and activation
        self.norm = nn.InstanceNorm2d(out_size)
        self.activation = nn.ReLU(inplace=True)
        self.dropout = nn.Dropout(dropout) if dropout else nn.Identity()

        # Optional attention layer for the skip connection
        self.attention = nn.Conv2d(out_size, out_size, 1) if use_attention else nn.Identity()

    def forward(self, x, skip_input):
        # Upsample and refine the feature map
        x = self.upconv(x)
        x = self.norm(x)
        x = self.activation(x)
        x = self.refine_conv(x)

        # Apply dropout if enabled
        x = self.dropout(x)

        # Apply attention to the skip connection, if enabled
        skip_input = skip_input * self.attention(skip_input)

        # Concatenate with skip connection
        x = torch.cat((x, skip_input), 1)

        return x

class Marker_Unet(nn.Module):
    def __init__(self, in_channels=3, out_channels=1):
        super(Marker_Unet, self).__init__()

        self.down1 = UNetDown(in_channels, 16, normalize=False)
        self.down2 = UNetDown(16, 32, dropout=0.5)
        self.down3 = UNetDown(32, 64, dropout=0.5)
        self.down4 = UNetDown(64, 64, normalize=False, dropout=0.5)

        self.up1 = UNetUp(64, 64, dropout=0.5)
        self.up2 = UNetUp(128, 32, dropout=0.5)
        self.up3 = UNetUp(64, 16)
        self.final = nn.Sequential(
            nn.Upsample(scale_factor=2),
            nn.ZeroPad2d((1, 0, 1, 0)),
            nn.Conv2d(32, out_channels, 4, padding=1),
            nn.Sigmoid()
        )
    def forward(self, x):
        # circle mask output
        d1 = self.down1(x)
        d2 = self.down2(d1)
        d3 = self.down3(d2)
        d4 = self.down4(d3)

        u1 = self.up1(d4, d3)
        u2 = self.up2(u1, d2)
        u3 = self.up3(u2, d1)
        unet_output = self.final(u3)

        return unet_output


class Marker_Unet_Deep(nn.Module):
    def __init__(self, in_channels=3, out_channels=1):
        super(Marker_Unet_Deep, self).__init__()

        # Downsampling path
        # Downsampling path with increased channels
        self.down1 = UNetDown_Enhanced(in_channels, 32, normalize=False)
        self.down2 = UNetDown(32, 64, dropout=0.5)
        self.down3 = UNetDown(64, 128, dropout=0.5)
        self.down4 = UNetDown_Enhanced(128, 256, dropout=0.5)

        # Bottleneck layers for global shape encoding
        self.bottleneck1 = nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1)
        self.bottleneck2 = nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1)

        # Upsampling path with adjusted channels for concatenation
        self.up1 = UNetUp_Enhanced(256, 128, dropout=0.5, use_attention=True)  # Concatenate with d3
        self.up2 = UNetUp(256, 64, dropout=0.5)  # Concatenate with d2
        self.up3 = UNetUp(128, 32)  # Concatenate with d1
        self.up4 = UNetUp_Enhanced(64, 16)  # Concatenate with initial input `x`

        # Final layer
        self.final = nn.Sequential(
            nn.Upsample(scale_factor=2),
            nn.ZeroPad2d((1, 0, 1, 0)),
            nn.Conv2d(16, out_channels, 4, padding=1),
            nn.Sigmoid()
        )

        # Final layer
        self.final = nn.Sequential(
            nn.Upsample(scale_factor=1),
            nn.ZeroPad2d((1, 0, 1, 0)),
            nn.Conv2d(19, out_channels, 4, padding=1),
            nn.Sigmoid()
        )

    def forward(self, x):
        # Downsampling path
        d1 = self.down1(x)
        d2 = self.down2(d1)
        d3 = self.down3(d2)
        d4 = self.down4(d3)

        # Bottleneck layers
        b1 = self.bottleneck1(d4)
        b2 = self.bottleneck2(b1)
        # Upsampling path with corrected concatenation
        u1 = self.up1(b2, d3)
        u2 = self.up2(u1, d2)
        u3 = self.up3(u2, d1)
        u4 = self.up4(u3, x)  # Adding final upsampling layer
        # Final output
        unet_output = self.final(u4)
        return unet_output
